### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by karabelnikov** [bnhf/pivpn-tap-web-ui#4]
Hello, friend! I need your help. I deployed your container and everything is fine, but when I connect the client, my main page drops out in the HTTP ERROR 500 error

Once the client is disconnected, the page loads again. The problem is that with any client connection, the main page crashes. Tell me what you need to submit to investigate the problem. I really want to use your project.

Thanks for the work, friend.

**Comment by bnhf** [comment]
@karabelnikov 

Please send me the output of ```pivpn -d``` from the command line and screenshots of ```Configuration - Settings``` and ```Configuration - OpenVPN Config``` from the WebUI, and we'll see what's up.

**Comment by bnhf** [comment]
@karabelnikov 

My apologies, but this is a somewhat limited project. I've expanded it slightly to include both TUN and TAP OpenVPN servers, but in both cases it has only ever been tested using PiVPN as the installation script and Debian (and its immediate derivatives) as the OS. The project assumes the directory structure, file naming conventions and so on, of PiVPN.

The original openvpn-web-ui project it's based on, used a two container approach, where the OpenVPN server was running in a container rather than on the host, to provide this predictable OpenVPN environment.

I can't really think of a reason why a client connecting would cause an issue with the home page, other than the obvious of the page being updated with that clients connection information. Have you tried using a different browser, or turning on developer mode to see anything notable pops up?

In the screenshot you sent me, the only issue I see is with the ```Server Address (external)``` which would typically be set to either a DDNS hostname of your OpenVPN server, or a static IP address assigned by your ISP if you have one -- not the address of your gateway router. This address is used for client settings file generation though, so it should not have a bearing on the issue you're experiencing.

**Comment by bnhf** [comment]
@karabelnikov 

Go ahead and post your server.conf file and your openvpn.log file, which would both be found in /etc/openvpn, and I'll see if there's anything obvious. Also, let me know if either of those files isn't present in that directory.

**Comment by karabelnikov** [comment]
@bnhf 

Friend, thank you for your feedback!

From the initial openvpn-web-ui project, I use only the web interface, I create only one container, as in your case.
I use OpenVPN on the host, through a script. From the original preoct only the web interface. But everything works there!

I tried different browsers and turned on developer mode, but I didn't see anything interesting. Server error 500 is most likely related to the incorrect
operation of js.

Server Address (external) I use dynamic, just in the screenshot I wrote for an example. I understand its purpose and how it is used.
I connect via a dynamic ip address. He's just changing. This is my first environment.

I have now made a clean virtual machine with debian. I have installed PiVPN + your project and the problem persists. So the problem is where at the root of your preoct.
I attach the result of pivpn -d

[Logs Download](https://mega.nz/file/IwJGmDJQ#Ey3yZKbihvgN3zZ4KOIPHJ1lFsjMwGqZFnovyVRdqpk)

**Comment by karabelnikov** [comment]
@bnhf

I do it all on Debian 10, could it be related to this?

**Comment by bnhf** [comment]
@karabelnikov 

So far I'm not able to reproduce this problem. This project uses the AdminLTE template which I did not modify, other than applying a dark theme. As a quick sanity check, I did a real-world test connecting a PC several thousand miles away to my home network, and everything worked as expected:

![Screenshot 2022-12-02 124245](https://user-images.githubusercontent.com/41088895/205375782-66906a7f-e96e-46bf-950f-6736517cbd0e.png)

There's a pretty long list of project dependencies though, and I updated all of them from 2017, which is the last time openvpn-web-ui was worked on. Maybe one of those projects introduced a difference?

I did have somebody report a problem a couple of weeks ago, that seems very similar to this, so I'll probably setup a TUN server as a further check.

**Comment by bnhf** [comment]
@karabelnikov 

No issues with Debian 10 that I'm aware of, one of my test servers is a Raspberry Pi running the Raspbian version of Buster.

**Comment by bnhf** [comment]
@karabelnikov 

OK, so I just spun up a Debian 11 VM using VirtualBox, and installed the usual suspects:

Docker
Portainer
Cockpit w/Navigator
PiVPN

and again connected from afar, this time using TUN instead of TAP:

![Screenshot 2022-12-02 151436](https://user-images.githubusercontent.com/41088895/205399360-6e18ed7a-cbe3-4395-864f-ba6eb01fec75.png)

Totally fresh installation, with everything up-to-date. This is going to be hard to fix if I can't duplicate the problem...

**Comment by bnhf** [comment]
@karabelnikov 

I think I know what's going on. I believe the problem is not Debian 10 itself, but the older version of OpenVPN in its repositories. There was a change in the way information from the OpenVPN Management interface is reported between 2.4 and 2.5. I fixed that when I updated from the original openvpn-web-ui project.

I would imagine there's a way to update OpenVPN to 2.5x (through backports or whatever) on older versions of Debian. It's late here, but I'll take a look at this tomorrow. Or, if you have a chance to check it out in the meantime, let me know what you find out.

**Comment by karabelnikov** [comment]
**@bnhf** 

Friend, thank you for your research. I am very grateful to you for your help. I did it all right!
Indeed, as you said, the problem lies in the OpenVPN version. The commands that your project sends are incompatible with the old versions of OpenVPN 2.4.X. Since you updated the dependencies to the latest versions, this caused a critical error and a crash of the main monitoring page. I connected the OpenVPN repository and updated my server to version 2.5.8. After restarting the server, I connected the client and the drop of the main page with monitoring is no longer observed. **[Here is my screenshot](https://mega.nz/file/k1xwWAgB#Z50DcMSOKoVBu3Ock5Ry7fUe3p2RBb1AXjTafRcZYYE)**.

Thank you so much for your help! I am very grateful to you. I think this post will help many others who are faced with such a problem. **You made a great project, I really like it!** 

**I have one more question, also very important!** For some reason, in the Configuration - Settings section in the Management interface address field, if you specify **localhost:2080**, or **127.0.0.1:2080**, or **debian:2080** (debian is the hostname), or **127.0.1.1:2080** (this is the ip of the hostname inside the host), then monitoring **does not work**! Shows In and Out **Mapping error MB**. **[Here is my screenshot](https://mega.nz/file/ctohkTpR#8OkJOfjOMN1oUQGSznJY6iOFo31rKPJPMd2JJe_MiU4)**. But if I specify the IP address of the interface (for example, the IP address of the interface 192.168.10.10), then **everything works**. The monitoring page shows clients and OpenVPN server data. In the OpenVPN configuration file I have written: management 0.0.0.0 2080. That is, the ability to listen to port 2080 on any interface. But! **It's not secure**, any user on my private network will be able to connect to my OpenVPN server and manage it!!! I want to register management 127.0.0.1 2080 so that there is only an access to the port inside the host. That is, register Management interface address 127.0.0.1:2080, or localhost:2080. But it doesn't work that way. Why can there be such a problem, friend?
**Is it possible to solve it somehow?**
Thanks!

**Comment by karabelnikov** [comment]
For information to other users. You can update your OpenVPN version using the information on this page: https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

@bnhf 
Friend, I would recommend you to specify in the requirements on the project page that the user needs OpenVPN version 2.5.X and higher. I think this will fix problems for many others in the future. Because this is not a feature of your project, but it is a feature of OpenVPN.
